<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Reservation;
use App\Models\User;
use App\Models\Restaurant;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ReservationSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::where('email', 'satonao@kredo.com')->first();
        $restaurant = Restaurant::first();

        if ($user && $restaurant) {
            $reservations = [
                [
                    'label' => 'Upcoming reservation',
                    'reservation_date' => '2026-04-20', 
                    'reservation_time' => '18:00:00',
                    'number_of_people' => 5,
                ],
                [
                    'label' => 'Past reservation',
                    'reservation_date' => '2026-04-10', 
                    'reservation_time' => '19:00:00',
                    'number_of_people' => 2,
                ],
            ];

            foreach ($reservations as $data) {
                Reservation::updateOrCreate(
                    [
                        'user_id'          => $user->id,
                        'restaurant_id'    => $restaurant->id,
                        'reservation_date' => $data['reservation_date'],
                    ],
                    [
                        'reservation_time' => $data['reservation_time'],
                        'reserved_at'      => now(), 
                        'number_of_people' => $data['number_of_people'],
                        'full_name'        => $user->first_name . ' ' . $user->last_name,
                        'phone'            => $user->tel,
                        'email'            => $user->email,
                        'special_requests' => $data['label'] . 'のテストデータです。',
                        'status'           => 'pending',
                        'visited_at'       => null,
                    ]
                );
            }
        }
        //  $now = Carbon::now();

        // DB::table('reservations')->insert([
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 1,
        //         'reservation_date' => '2026-04-25',
        //         'reservation_time' => '18:00:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Yuna Sato',
        //         'phone'            => '090-1111-1111',
        //         'email'            => 'user1@test.com',
        //         'special_requests' => 'Window seat if available.',
        //         'status'           => 'pending',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 2,
        //         'reservation_date' => '2026-04-25',
        //         'reservation_time' => '19:00:00',
        //         'number_of_people' => 4,
        //         'full_name'        => 'Hana Suzuki',
        //         'phone'            => '090-2222-2222',
        //         'email'            => 'user2@test.com',
        //         'special_requests' => 'Birthday dinner.',
        //         'status'           => 'confirmed',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 3,
        //         'reservation_date' => '2026-04-26',
        //         'reservation_time' => '12:30:00',
        //         'number_of_people' => 3,
        //         'full_name'        => 'Mio Tanaka',
        //         'phone'            => '090-3333-3333',
        //         'email'            => 'user3@test.com',
        //         'special_requests' => 'Need a child seat.',
        //         'status'           => 'pending',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 4,
        //         'reservation_date' => '2026-04-26',
        //         'reservation_time' => '13:00:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Rina Kobayashi',
        //         'phone'            => '090-4444-4444',
        //         'email'            => 'user4@test.com',
        //         'special_requests' => null,
        //         'status'           => 'completed',
        //         'visited_at'       => '2026-04-26 13:00:00',
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 5,
        //         'reservation_date' => '2026-04-27',
        //         'reservation_time' => '18:30:00',
        //         'number_of_people' => 5,
        //         'full_name'        => 'Aya Yamamoto',
        //         'phone'            => '090-5555-5555',
        //         'email'            => 'user5@test.com',
        //         'special_requests' => 'Allergic to shrimp.',
        //         'status'           => 'confirmed',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 6,
        //         'reservation_date' => '2026-04-28',
        //         'reservation_time' => '17:30:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Nanami Ito',
        //         'phone'            => '090-6666-6666',
        //         'email'            => 'user6@test.com',
        //         'special_requests' => 'Quiet table preferred.',
        //         'status'           => 'cancelled',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 7,
        //         'reservation_date' => '2026-04-29',
        //         'reservation_time' => '19:30:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Saki Watanabe',
        //         'phone'            => '090-7777-7777',
        //         'email'            => 'user7@test.com',
        //         'special_requests' => null,
        //         'status'           => 'pending',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 25,
        //         'user_id'          => 8,
        //         'reservation_date' => '2026-04-30',
        //         'reservation_time' => '20:00:00',
        //         'number_of_people' => 6,
        //         'full_name'        => 'Yui Nakamura',
        //         'phone'            => '090-8888-8888',
        //         'email'            => 'user8@test.com',
        //         'special_requests' => 'Anniversary dinner.',
        //         'status'           => 'confirmed',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],

        //     [
        //         'restaurant_id'    => 26,
        //         'user_id'          => 1,
        //         'reservation_date' => '2026-05-01',
        //         'reservation_time' => '18:00:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Yuna Sato',
        //         'phone'            => '090-1111-1111',
        //         'email'            => 'user1@test.com',
        //         'special_requests' => null,
        //         'status'           => 'pending',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 27,
        //         'user_id'          => 2,
        //         'reservation_date' => '2026-05-01',
        //         'reservation_time' => '19:00:00',
        //         'number_of_people' => 3,
        //         'full_name'        => 'Hana Suzuki',
        //         'phone'            => '090-2222-2222',
        //         'email'            => 'user2@test.com',
        //         'special_requests' => 'Corner seat.',
        //         'status'           => 'confirmed',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 28,
        //         'user_id'          => 3,
        //         'reservation_date' => '2026-05-02',
        //         'reservation_time' => '12:00:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Mio Tanaka',
        //         'phone'            => '090-3333-3333',
        //         'email'            => 'user3@test.com',
        //         'special_requests' => null,
        //         'status'           => 'completed',
        //         'visited_at'       => '2026-05-02 12:00:00',
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 29,
        //         'user_id'          => 4,
        //         'reservation_date' => '2026-05-02',
        //         'reservation_time' => '18:30:00',
        //         'number_of_people' => 4,
        //         'full_name'        => 'Rina Kobayashi',
        //         'phone'            => '090-4444-4444',
        //         'email'            => 'user4@test.com',
        //         'special_requests' => 'Vegetarian option if possible.',
        //         'status'           => 'pending',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 30,
        //         'user_id'          => 5,
        //         'reservation_date' => '2026-05-03',
        //         'reservation_time' => '17:00:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Aya Yamamoto',
        //         'phone'            => '090-5555-5555',
        //         'email'            => 'user5@test.com',
        //         'special_requests' => null,
        //         'status'           => 'cancelled',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 31,
        //         'user_id'          => 6,
        //         'reservation_date' => '2026-05-03',
        //         'reservation_time' => '19:30:00',
        //         'number_of_people' => 5,
        //         'full_name'        => 'Nanami Ito',
        //         'phone'            => '090-6666-6666',
        //         'email'            => 'user6@test.com',
        //         'special_requests' => 'Near entrance is okay.',
        //         'status'           => 'confirmed',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 32,
        //         'user_id'          => 7,
        //         'reservation_date' => '2026-05-04',
        //         'reservation_time' => '18:00:00',
        //         'number_of_people' => 2,
        //         'full_name'        => 'Saki Watanabe',
        //         'phone'            => '090-7777-7777',
        //         'email'            => 'user7@test.com',
        //         'special_requests' => null,
        //         'status'           => 'pending',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 33,
        //         'user_id'          => 8,
        //         'reservation_date' => '2026-05-04',
        //         'reservation_time' => '20:00:00',
        //         'number_of_people' => 4,
        //         'full_name'        => 'Yui Nakamura',
        //         'phone'            => '090-8888-8888',
        //         'email'            => 'user8@test.com',
        //         'special_requests' => 'Window seat preferred.',
        //         'status'           => 'confirmed',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        //     [
        //         'restaurant_id'    => 34,
        //         'user_id'          => 1,
        //         'reservation_date' => '2026-05-05',
        //         'reservation_time' => '18:30:00',
        //         'number_of_people' => 3,
        //         'full_name'        => 'Yuna Sato',
        //         'phone'            => '090-1111-1111',
        //         'email'            => 'user1@test.com',
        //         'special_requests' => 'Business dinner.',
        //         'status'           => 'pending',
        //         'visited_at'       => null,
        //         'created_at'       => $now,
        //         'updated_at'       => $now,
        //     ],
        // ]);
    }
}