<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('restaurants')->insert([
            [
                'restaurant_name'   => 'Sakura Dining',
                'email'             => 'sakura@test.com',
                'phone'             => '090-1111-1111',
                'prefecture'        => 'Osaka',
                'city'              => 'Osaka City',
                'address_line'      => '1-1-1 Umeda',
                'opening_hours'     => '11:00 - 21:00',
                'description'       => 'A cozy Japanese restaurant for demo use.',
                'category_id'       => 1,
                'reservation_limit' => 20,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Ocean Table',
                'email'             => 'ocean@test.com',
                'phone'             => '090-2222-2222',
                'prefecture'        => 'Tokyo',
                'city'              => 'Shibuya',
                'address_line'      => '2-2-2 Shibuya',
                'opening_hours'     => '10:00 - 22:00',
                'description'       => 'Seafood restaurant for demo login.',
                'category_id'       => 1,
                'reservation_limit' => 15,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Kyoto Garden',
                'email'             => 'kyoto@test.com',
                'phone'             => '090-3333-3333',
                'prefecture'        => 'Kyoto',
                'city'              => 'Kyoto City',
                'address_line'      => '3-3-3 Gion',
                'opening_hours'     => '11:00 - 20:00',
                'description'       => 'Traditional Kyoto cuisine.',
                'category_id'       => 1,
                'reservation_limit' => 20,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Nagoya Grill',
                'email'             => 'nagoya@test.com',
                'phone'             => '090-4444-4444',
                'prefecture'        => 'Aichi',
                'city'              => 'Nagoya',
                'address_line'      => '4-4-4 Sakae',
                'opening_hours'     => '10:00 - 22:00',
                'description'       => 'Famous for miso katsu.',
                'category_id'       => 1,
                'reservation_limit' => 15,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Fukuoka Ramen',
                'email'             => 'fukuoka@test.com',
                'phone'             => '090-5555-5555',
                'prefecture'        => 'Fukuoka',
                'city'              => 'Hakata',
                'address_line'      => '5-5-5 Hakata',
                'opening_hours'     => '11:00 - 23:00',
                'description'       => 'Authentic tonkotsu ramen.',
                'category_id'       => 1,
                'reservation_limit' => 10,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Sapporo Snow',
                'email'             => 'sapporo@test.com',
                'phone'             => '090-6666-6666',
                'prefecture'        => 'Hokkaido',
                'city'              => 'Sapporo',
                'address_line'      => '6-6-6 Sapporo',
                'opening_hours'     => '10:00 - 21:00',
                'description'       => 'Seafood and miso ramen.',
                'category_id'       => 1,
                'reservation_limit' => 12,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Kobe Steak House',
                'email'             => 'kobe@test.com',
                'phone'             => '090-7777-7777',
                'prefecture'        => 'Hyogo',
                'city'              => 'Kobe',
                'address_line'      => '7-7-7 Kobe',
                'opening_hours'     => '12:00 - 22:00',
                'description'       => 'Premium Kobe beef.',
                'category_id'       => 1,
                'reservation_limit' => 8,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Okinawa Breeze',
                'email'             => 'okinawa@test.com',
                'phone'             => '090-8888-8888',
                'prefecture'        => 'Okinawa',
                'city'              => 'Naha',
                'address_line'      => '8-8-8 Naha',
                'opening_hours'     => '11:00 - 20:00',
                'description'       => 'Okinawan local food.',
                'category_id'       => 1,
                'reservation_limit' => 10,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Hiroshima Grill',
                'email'             => 'hiroshima@test.com',
                'phone'             => '090-9999-9999',
                'prefecture'        => 'Hiroshima',
                'city'              => 'Hiroshima City',
                'address_line'      => '9-9-9 Hiroshima',
                'opening_hours'     => '11:00 - 21:00',
                'description'       => 'Okonomiyaki specialty.',
                'category_id'       => 1,
                'reservation_limit' => 15,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'restaurant_name'   => 'Sendai Kitchen',
                'email'             => 'sendai@test.com',
                'phone'             => '090-0000-0000',
                'prefecture'        => 'Miyagi',
                'city'              => 'Sendai',
                'address_line'      => '10-10-10 Sendai',
                'opening_hours'     => '10:00 - 22:00',
                'description'       => 'Gyutan and local dishes.',
                'category_id'       => 1,
                'reservation_limit' => 18,
                'approval_status'   => 'approved',
                'status'            => 'published',
                'approved_at'       => $now,
                'password'          => bcrypt('password'),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ]);
    }
}
